### PR TITLE
 Introduction of maximal frequency for ThermalDisplacements class 

### PR DESCRIPTION
**Pull request by JaGeo**
I would like to introduce a maximal frequency for the calculation of the thermal displacements. This would be handy for some analysis of the thermal displacements.  I hope this is okay.

### CODE REVIEW

**Comment by atztogo** [comment]
I will think.

**Comment by atztogo** [comment]
I made max-freq-for-td branch. In it, --fmin and --fmax are used to specify them. The tag names are FMIN and FMAX, respectively. Now --cutoff-freq (CUTOFF_FREQUENCY) is inactive for this calculation. If it works, I will release this.

**Comment by JaGeo** [comment]
Thank you very much for your effort. I have tested it. So far, it works very well. 
Some small suggestions: Maybe you could keep "--cutoff-freq" (CUTOFF_FREQUENCY) in the parser as an alternative to FMIN. It might take some time until everyone has adjusted. Also, FMAX is not printed to the output file so far.

**Comment by atztogo** [comment]
I don't want to put more effort for this since I think this feature is not very popular. So I want users to realize it by themselves reading the document.

**Comment by JaGeo** [comment]
Okay, I see. Keeping "--cutoff-freq" (CUTOFF_FREQUENCY) as an alternative to FMIN still might be a good idea.

**Comment by atztogo** [comment]
I think it's not a good design. It will be a possible source of bugs. I will just show an error message when a user using --cutoff-freq together with thermal displacements.

**Comment by JaGeo** [comment]
Okay. Thanks a lot.

**Comment by atztogo** [comment]
I will write document and then release it. I will close this pull request.

**Pull request closed without merging**
