### PR TITLE
Fhiaims update

### PR DESCRIPTION
**Pull request by Floyd4K**
I updated the FHIaims part of phonopy to be compatible with the PhonopyAtoms class, with python3 and newer matplotlib versions.
The old version was unusable in the last months.

### CODE REVIEW

**Comment by atztogo** [comment]
This is not the correct direction.
I said to your colleague that I will not keep scripts/phonopy-FHI-aims in phonopy package. You should simply do the same way as other calculator interfaces to provide FHI-aims users be able to use many features of phonopy.

**Comment by Floyd4K** [comment]
I totally agree. I'm teaching in the way you recommend. However, several people in our group still use the tool and I think it should be at least functional, before it will be removed in the future.

The changes are just in place to make the script functional and keep compatibility. There is no active development.

**Comment by atztogo** [comment]
I see. This time, I will merge them. But I will remove ``script/phonopy-FHI-aims`` as I mentioned to your colleague before at some future.

**Comment by Floyd4K** [comment]
Thank you. I will talk to the respective people and discuss the future of FHIaims integration within phonopy with them.
Florian

**Pull request merged**
