### PR TITLE
add pyproject.toml to declare numpy as build dependency

### PR DESCRIPTION
**Pull request by flokno**
Solves https://github.com/atztogo/phonopy/issues/53

### CODE REVIEW

**Comment by atztogo** [comment]
Do you know what are these warnings appearing in pip install?

```
  WARNING: Missing build requirements in pyproject.toml for file:///Users/togo/code/phonopy.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
```

**Comment by flokno** [comment]
You are right, I forgot to include `wheel` in the requirements, I'll add them.

**Comment by flokno** [comment]
I replace this PR by https://github.com/atztogo/phonopy/pull/98

**Comment by atztogo** [comment]
I just don't know these stuffs. Thanks.

**Comment by flokno** [comment]
You're welcome! I didn't know about this as well, until recently when I started using `poetry` to package my python projects. `poetry` is a great tool, but also very strict and picky with dependencies, which forced me to look into the business of python packaging a bit more.
But also I'm far from being an expert, for sure.

**Pull request closed without merging**
