### PR TITLE
Ft add summary file output data flags

### PR DESCRIPTION
**Pull request by pjcon**
Update Phonopy user interface flags/settings to output extra data to phonopy.yaml, including: force constants, force sets, dielectric tensor, born effective charges, displacements.

Flags (store_true)/settings (set to .TRUE.): --include-fc/INCLUDE_FC, --include-fs/INCLUDE_FS, --include-eps/INCLUDE_EPS, --include-bec/INCLUDE_BEC, --include-disp/INCLUDE_DISP, --include-all/INCLUDE_ALL.

I have also fixed a few parts that caused bugs in `class PhonopyConfParser`, and slightly changed how output options are sent through `finalize_phonopy` to `PhonopyYaml`, but the change is relatively transparent.

### CODE REVIEW

**Comment by pjcon** [comment]
I have included a small stub test called `test_write_phonopy_yaml_extra` in interface/test_phonopy_yaml.py but I'm not sure how rigorous you want it in comparison to the current test.

**Comment by atztogo** [comment]
Thanks for this nice option and  also for fixing my mistakes. One thing, I want to discuss. You separate Born effective charges and dielectric constants, but in phonopy they are used as a couple always, so maybe one option for both is convenient. How do you think?

**Comment by pjcon** [comment]
Ok. I'll merge them at the front end using the flag `--include-born`, but I'll keep them separate on the back end to maintain individual get/set control for each output data type in cui/settings.py

**Comment by atztogo** [comment]
Thanks. Merged to develop branch.

**Comment by atztogo** [comment]
I close this PR.

**Pull request closed without merging**
